### PR TITLE
Update crawler.py

### PR DESCRIPTION
**Pull request by syedan**

### CODE REVIEW

**Comment by syedan** [comment]
@syedan hi

**Comment by syedanees15** [comment]
@syedan testing

**Comment by syedan** [comment]
@syedanees15  ehllo

**Comment by syedan** [comment]
test

**Comment by syedan** [comment]
testing

**Comment by syedan** [comment]
@syedanees15  Ready for deployment

**Comment by syedan** [comment]
syedanees85 ready for deployment

**Comment by syedan** [comment]
Anees ready

**Comment by syedan** [comment]
Anees ready

**Comment by syedan** [comment]
@syedanees85 check

**Comment by syedan** [comment]
@syedanees85 hello

**Comment by syedan** [comment]
@syedanees85 sadf

**Comment by syedan** [comment]
@syedanees85 asdfasdf

**Comment by syedan** [comment]
asdfasdf

**Comment by syedan** [comment]
asdf

**Comment by syedan** [comment]
@anees1

**Pull request closed without merging**
